config/routes.rb
Rails.application.routes.draw do
  # Defines the root path route ("/")
  root "welcome#index"
  
  # Auth
  get "signup", to: "users#new"
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  get "logout", to: "sessions#destroy"

  # Auth with Google
  #get 'login', to: 'logins#new'
  #get 'login/create', to: 'logins#create', as: :create_login

  #resources :books do
  #  member do
  #   put "add", to: "books#library"
  #    delete :destroy
  #  end
  #end

  resources :users
  resources :users, only: [:new, :create, :show] do
    resources :books, only: [:index]
  end


  resources :books
  
  resources :libraries do
    resources :books
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
  has_one_attached :thumbnail 
  validates :title, :author, :thumbnail, presence: true
  validates :user_id, presence: true
  #validates :title, :isbn, :author, :thumbnail, :description, :state, presence: true  - Google books api

  belongs_to :user
  has_many :libraries
  has_many :added_books, through: :libraries, source: :user
end

app/models/library.rb
class Library < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  before_save { self.email = email.downcase }

  validates :email, presence: true, uniqueness: true
  validates :name, :password, presence: true

  has_many :books
  has_many :libraries

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend

  helper_method :current_user
  helper_method :user_signed_in?

  def current_user
    User.find_by(id: session[:user_id])
  end

  def user_signed_in?
    !current_user.nil?
  end

  def authenticate_user!
    redirect_to root_path, alert: t("common.auth.authenticate_user") unless user_signed_in?
  end
  
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]
  before_action :set_book, only: [:show, :edit, :update]

  def index
    @pagy, @books = pagy(Book.all)
  end


  def new
    @book = Book.new
  end


  def create
    @book = current_user.books.build(book_params)
    if @book.save
      return redirect_to current_user, notice: t(".notice")
    end

    render :new
  end


  def update
    @book = Book.find params[:id]

    if @book.update book_params
      return redirect_to @book, notice: t(".notice")
    end

    render :edit
  end


  def destroy
    @book = Book.find params[:id]
    @book.destroy
    redirect_to book_path, notice: t(".notice")
  end


  def show; end

  def edit; end

  
  private

  def book_params
    params.require(:book).permit(:title, :author, :thumbnail, :description, :state  )
    #params.require(:book).permit(:title, :isbn, :author, :thumbnail, :description, :state ) - Google books api
  end

  def set_book
    @book = Book.find params[:id]
  end

end

app/controllers/libraries_controller.rb
class LibrariesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :update, :destroy]
  
  def index
    @library = Library.find(params[:id])
  end

end

app/controllers/logins_controller.rb
# app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  def new
  end

  def create
    if user = authenticate_with_google
      cookies.signed[:user_id] = user.id
      redirect_to user
    else
      redirect_to new_session_url, alert: 'authentication_failed'
    end
  end

  private
    def authenticate_with_google
      if id_token = flash[:google_sign_in][:id_token]
        User.find_by google_id: GoogleSignIn::Identity.new(id_token).user_id
      elsif error = flash[:google_sign_in][:error]
        logger.error "Google authentication error: #{error}"
        nil
      end
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: t('.notice')
    else
      flash.now[:alert] = t('.alert')
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: t('.notice')
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params

    if @user.save
      session[:user_id] = @user.id
      return redirect_to root_url, notice: t(".notice")
    end

    render :new 
  end

  def show
    @user = User.find(params[:id])
    @pagy, @user_books = pagy(@user.books)
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    #flash[:notice] = "Welcome Rails App"
    #flash[:alert] = "Exist an error with Rails App"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend

  def flash_class(key)
    case key
      when "notice" then "is-success"
      when "alert" then "is-danger"
    end
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/libraries_helper.rb
module LibrariesHelper
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/books/_book.html.erb
<section class="card column is-3 mg card-size">
  <div class="card-image p-4">
    <% if book.thumbnail.attached? %>
      <figure class="image is-4by3">
        <%= image_tag(url_for(book.thumbnail)) %>
      </figure>
    <%end%>

    <div class="card-content center-text">
      <div class="media">
        <div class="media-content">
          <p class="title name-book is-4"><%= link_to( book.title, book_path(book))%></p>
          <p class="is-6"><%= book.author %></p>
          <p class="is-6"><%= book.description %></p>
        </div>
      </div>
    </div>

    <div class="controls pt2 center-text">
      <% if user_signed_in? %>
        <%= link_to 'Edit', edit_book_path(book), class:"button is-small is-rounded small-color-btn" %>
        <%= link_to 'Delete', book, data: { "turbo-method": :delete, notice: "Are you sure? "}, class:"button is-small is-rounded small-color-btn" %>     
      <% end %>
    </div>
  </div>
</section>

app/views/books/_form.html.erb
<div class="form-layout">
  <%= form_for @book, builder: BulmaFormBuilder, local: true, data: { turbo: false } do |f| %>
    <%= f.form_error %>

      <div class="field">
        <%= f.label :title, class:"label"%>
        <div class="control">
          <%= f.text_field :title, class:"input"%>
        </div>
        <%= f.field_error :title %>
      </div>

      <!--<div class="field">
        <%= f.label :isbn, class:"label"%>
        <div class="control">
          <%= f.text_field :isbn, class:"input"%>
        </div>
        <%= f.field_error :isbn %>
      </div> -->

      <div class="field">
        <%= f.label :author, class:"label"%>
        <div class="control">
          <%= f.text_field :author, class:"input"%>
        </div>
        <%= f.field_error :author %>
      </div>

      <div class="field">
        <%= f.label :description, class:"label"%>
        <div class="control">
          <%= f.text_field :description, class:"input"%>
        </div>
        <%= f.field_error :description %>
      </div>

      <div class="field">
        <%= f.label :thumbnail, class:"label"%>
        <div class="control">
          <%= f.file_field :thumbnail, class:"input"%>
        </div>
        <%= f.field_error :thumbnail %>
      </div>

      <div class="checkbox">
        <%= f.label :state, class:"label is-inline"%>
        <%= f.check_box :state, class:"checkbox"%>
      </div>
      <br>

    <%= f.submit class:"button btn-color mt-3 mb-4"%><br>
    <%= link_to "Volver", root_path, class:"add-link"%>
    
  <% end %>
</form>

app/views/books/create.html.erb
<h1>Books#create</h1>
<p>Find me in app/views/books/create.html.erb</p>

app/views/books/edit.html.erb
<h1 class="center-text mt-4">Editar Libro</h1>

<%= render "form" %>

app/views/books/index.html.erb
<section class="columns is-desktop is-multiline">
  <%= render @books %>
</section>

<%== pagy_bulma_nav(@pagy) %>

app/views/books/new.html.erb
<h1 class="center-text mt-4">Añade un libro a tu librería</h1>

<%= render "form" %>

app/views/books/show.html.erb
<section class="container-card">
  <div class="book-card center-text">
    <h1 class="title"><%= @book.title %><h1>
    <figure class="is-128x128 center">
      <%= image_tag(url_for(@book.thumbnail)) %>
    </figure>
    <div class="center-text">
      <p><%= @book.author %></p>
      <p><%= @book.description %></p>
    </div>
  </div>
</section>
<%= link_to('Volver', current_user, class: 'add-link pb-6') %>

app/views/books/update.html.erb
<h1>Books#update</h1>
<p>Find me in app/views/books/update.html.erb</p>

app/views/common/_flash_messages.html.erb
<% flash.each do |key, value| %>
  <div class="notification <%= flash_class(key) %>">
    <%= value%>
  </div>
<% end %>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Doreads</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header>
      <%= render "navigation/navbar" %>
    </header>
    <section>
      <div class="container">
        <%= render "common/flash_messages" %> 
        <%= yield %>
      </div>
    </section>

  </body>
</html>

app/views/libraries/index.html.erb
<section>
  <h1><%= @library.user %></h1>
  <% if @library_books.exists? %>
    <div class="book-grid">
      <%= render "books/book", book: @book %>
    </div>
  <% else %>
    <article class="message">
      <div class="message-body">You haven't added any books to your library yet. <%= link_to 'Add some', root_path %>.</div>
    </article>
  <% end %>
</section>

app/views/navigation/_navbar.html.erb
<nav class="navbar nav-size" role="navigation" aria-label="main navigation">
  <div id="navbarBasicExample" class="navbar-menu nav-menu">
    <div class="navbar-start">
      <%= link_to('Inicio', root_path, class: 'navbar-item nav-item') %>
    </div>

    <div class="navbar-end">
      <div class="navbar-item nav-item">
        <div class="buttons">
          <% if user_signed_in? %>
            <%= link_to "Añadir un libro", new_book_path, class:'navbar-item nav-item is-hoverable'%>
            <%= link_to('Tu Librería', current_user, class: 'navbar-item nav-item is-hoverable') %>
            <!--<%= link_to('Tu Librería', libraries_path, class: 'navbar-item nav-item is-hoverable') %>-->
            <div class="navbar-item has-dropdown is-hoverable">
              <a class="navbar-link nav-item">
                <%= current_user.name %>
              </a>
              <div class="navbar-dropdown">
                <%= link_to('Salir', logout_path, class: 'navbar-item nav-item is-hoverable') %>
              </div>
            </div>
          <% else %>
            <%= link_to('Crear cuenta', signup_path, class: 'button is-black nav-item is-hoverable') %>
            <%= link_to('Iniciar sesión', login_path, class: 'button is-light nav-item is-hoverable') %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</nav>

app/views/users/new.html.erb
<div class="form-layout">
  <h1 class="title">Crea tu cuenta</h1>
  <%= form_for @user, builder: BulmaFormBuilder, local: true, data: { turbo: false } do |f| %>

    <%= f.form_error %>

    <div class="field">
      <%= f.label :name, class: "label" %>
      <div class="control">
        <%= f.text_field :name, class: "input" %>
      </div>
      <%= f.field_error :name %>
    </div>

    <div class="field">
      <%= f.label :email, class: "label"  %>
      <div class="control">
        <%= f.text_field :email, class: "input is-normal" %>
      </div>
      <%= f.field_error :email %>
    </div>

    <div class="field">
      <%= f.label :password, class: "label"  %>
      <div class="control">
        <%= f.password_field :password, class: "input is-normal" %>
      </div>
      <%= f.field_error :password %>
    </div>

    <%= f.submit class: "button btn-color"%><br>
  <% end %>
</div>

app/views/users/show.html.erb
<section class="mb-6">
  <h1 class="title pt-6 is-size-2">¡Hola, <%= @user.name || @user.email %>!</h1>
  <p class="is-size-5">Has añadido <%= @user_books.count %> libro(s) a tu librería.</p>
  <div class="columns is-desktop is-multiline pt-6">
    <%= render @user_books, locals: {user: @user}%>
  </div>
  <div class="pg mb-4 px-6">
    <%== pagy_bulma_nav(@pagy) %>
  </div>
</section>

app/views/welcome/index.html.erb
<section class="is-light layout">
  <div class="hero-body container mg-t">
    <div class="img-container">
      <a href="/"><img src="https://i.ibb.co/x3G1NWf/doreads-logo.png" alt="doreads-logo", class="img-logo"></a>
    <!--<img src="assets/doreads-logo.png" alt="Logo-DoReads" class="img-logo">-->
    </div>
    <p class="subtitle has-text-centered">
      <% if user_signed_in? %>
        <%= link_to('Añade un nuevo libro a tu librería', new_book_path, class: 'add-link') %>
      <%end%>
    </p>
  </div>
</section>